### ISSUE TITLE
Build fails Jellyfish 2.3.0

### ISSUE THREAD

**Issue by Parsoa** [gmarcais/Jellyfish#149]
I get the following output when running make on Jellyfish 2.3.0 tarball on Ubuntu 18.0.2 LTS. Configure runs just fine but seems like it's not finding some files related to python bindings during build. Will build find if I configure and make without python bindings.

```
make  all-am
make[1]: Entering directory '/root/jellyfish-2.3.0'
  CXX      lib/rectangular_binary_matrix.lo
  CXX      lib/mer_dna.lo
  CXX      lib/storage.lo
  CXX      lib/allocators_mmap.lo
  CXX      lib/misc.lo
  CXX      lib/int128.lo
  CXX      lib/thread_exec.lo
  CXX      lib/jsoncpp.lo
  CXX      lib/time.lo
  CXX      lib/generator_manager.lo
  CXXLD    libjellyfish-2.0.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      swig/python/swig_python__dna_jellyfish_la-swig_wrap.lo
  CXXLD    swig/python/_dna_jellyfish.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      sub_commands/jellyfish.o
  CXX      sub_commands/count_main.o
  CXX      sub_commands/info_main.o
  CXX      sub_commands/dump_main.o
  CXX      sub_commands/histo_main.o
  CXX      sub_commands/stats_main.o
  CXX      sub_commands/merge_main.o
  CXX      sub_commands/bc_main.o
  CXX      sub_commands/query_main.o
  CXX      sub_commands/cite_main.o
  CXX      sub_commands/mem_main.o
  CXX      jellyfish/merge_files.o
  CXXLD    bin/jellyfish
  PYTHONC  swig/python/__init__.pyc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/py_compile.py", line 106, in compile
    with open(file, 'U') as f:
IOError: [Errno 2] No such file or directory: 'swig/python/dna_jellyfish.py'
Makefile:2849: recipe for target 'swig/python/__init__.pyc' failed
make[1]: *** [swig/python/__init__.pyc] Error 1
make[1]: Leaving directory '/root/jellyfish-2.3.0'
Makefile:977: recipe for target 'all' failed
make: *** [all] Error 2
make  install-am
make[1]: Entering directory '/root/jellyfish-2.3.0'
  PYTHONC  swig/python/__init__.pyc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/py_compile.py", line 106, in compile
    with open(file, 'U') as f:
IOError: [Errno 2] No such file or directory: 'swig/python/dna_jellyfish.py'
Makefile:2849: recipe for target 'swig/python/__init__.pyc' failed
make[1]: *** [swig/python/__init__.pyc] Error 1
make[1]: Leaving directory '/root/jellyfish-2.3.0'
Makefile:2643: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by fplaza** [comment]
I have the same problem.
The file setup.py is missing in the swig/python directory

**Comment by rafaeldelucena** [comment]
@fplaza can you provide a PR which fixes it?

**Comment by fplaza** [comment]
I am afraid I can't.
I guess the entire package has to be rebuilt with autoreconf
Meanwhile, you can use older versions of jellyfish

**Comment by gmarcais** [comment]
The distribution tarball was regenerated. Not sure why these files were missing in the first place. It should compile fine now.
