### ISSUE TITLE
jellyfish doesn't recognize "qmerge" and "q" options 

### ISSUE THREAD

**Issue by janniel091418** [gmarcais/Jellyfish#151]
I am currently using RAMPART software. I figured out that the error message i received in the command line is reflected in a folder inside RAMPART and turns out it is because of jellyfish? not so sure about this. please help me. This the error i get from my file 

PATH

> /home/hydra/Desktop/5_30_19-Try_rampart/190613/rampart_out/1_mecq/quake/ecoli

RAMPART20190925_025346-1_mecq-rampart_out-1_mecq-name_quake_ecoli.log

> `count:` invalid option -- 'q'
Use --usage or --help for some help
Unknown command 'qmerge'

> Usage: jellyfish <cmd> [options] arg...
Where <cmd> is one of: count, bc, info, stats, histo, dump, merge, query, cite, mem, jf.
Options:
  --version        Display version
  --help           Display this message
Traceback (most recent call last):
  File "/home/hydra/anaconda3/bin/quake.py", line 324, in <module>
    main()
  File "/home/hydra/anaconda3/bin/quake.py", line 89, in main
    jellyfish(options.readsf, options.reads_listf, options.k, ctsf, quality_scale, options.hash_size, options.proc)
  File "/home/hydra/anaconda3/bin/quake.py", line 290, in jellyfish
    os.rename('%s.dbm_0' % output_pre, '%s.dbm' % output_pre)
FileNotFoundError: [Errno 2] No such file or directory: '/home/hydra/Desktop/5_30_19-Try_rampart/190613/rampart_out/1_mecq/quake/ecoli/readsListFile.dbm_0' -> '/home/hydra/Desktop/5_30_19-Try_rampart/190613/rampart_out/1_mecq/quake/ecoli/readsListFile.dbm'`

Currently using
jellyfish 2.3.0
python 3.6.7
quake 0.3

**Comment by gmarcais** [comment]
Quake uses version 1 of Jellyfish. The -q switch of count and qmerge subcommand do not exist in version 2.

**Comment by janniel091418** [comment]
Thank you for your kind response! But it seems like it produce another error. Same with this [https://github.com/atifrahman/HAWK/issues/2](url)

 I applied the solution, create the `dump_numeric patch` in my jellyfish directory 
> /home/hydra/Downloads/jellyfish-1.1.11/jellyfish

 but nothing seems to happen. I don't know if i done this correctly
`You should be able to apply it on the file 'dump_main.cc' in the jellyfish dir with:
patch -p1 < /path/to/dump_numeric.patch`

Thanks, I appreciate all the help :+1:
