### ISSUE TITLE
epic-effective cannot find jellyfish

### ISSUE THREAD

**Issue by IanCodes** [gmarcais/Jellyfish#84]
Hi,

I have installed epic and jellyfish in a virtualenv:
virtualenv venv.epic_0.1.25
. /path/venv.epic_0.1.25/bin/activate
pip install bioepic
pip install jellyfish

When I try to run epic-effective as:
epic-effective --read-length=76 --nb-cpu=12 oviAri3_BASE.fa

I get the following error:
Temporary directory: /tmp/86174.1.C6320-512-haswell.q (File: effective_genome_size, Log level: INFO, Time: Tue, 14 Mar 2017 16:40:11 )
File analyzed: oviAri3_BASE.fa (File: effective_genome_size, Log level: INFO, Time: Tue, 14 Mar 2017 16:40:11 )
Genome length: 2587507083 (File: effective_genome_size, Log level: INFO, Time: Tue, 14 Mar 2017 16:40:11 )
/bin/sh: jellyfish: command not found
/bin/sh: jellyfish: command not found
Traceback (most recent call last):
  File "/mnt/fls01-home01/user/virtualenvs/venv.epic_0.1.25/bin/epic-effective", line 38, in <module>
    effective_genome_size(fasta, read_length, nb_cpu, tmpdir)
  File "/mnt/fls01-home01/user/virtualenvs/venv.epic_0.1.25/lib/python2.7/site-packages/epic/scripts/effective_genome_size.py", line 56, in effective_genome_size
    shell=True)
  File "/opt/gridware/depots/4baff5c5/el7/pkg/apps/python/2.7.8/gcc-4.8.5/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'jellyfish stats /tmp/86174.1.C6320-512-haswell.q/oviAri3_BASE.fa.jf' returned non-zero exit status 127
rm: cannot remove ‘/tmp/86174.1.C6320-512-haswell.q/oviAri3_BASE.fa.jf’: No such file or directory

Thanks.

**Comment by IanCodes** [comment]
Sorry meant to put this on the epic page
